### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by RavenheadJB** [Project-Lunar/Project-Lunar-Issue-Tracker#31]
I'm getting this error as soon as i click Yes on the question for the interactive install guide.

System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at ProjectLunarUI.frmGameManager.FrmGameManager_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Is there any way around this?

I'm using windows 10 64bit

**Comment by Stonerkid** [comment]
I can't install it either, but the problem is that windows 10 doesn't recognize de .exe file and automatically deletes it once you have obtained it with winrar. First time I see something so odd.

OK, just discovered that the downloaded file is version 0.0.0. for _ProjectLunar-installer.zip_ wtf??

**Comment by Stonerkid** [comment]
Just read a few comments from people in Youtube and they have the same issue. There must be something wrong with the downloads, hope you can fix it.

**Comment by ineedhelpplz6** [comment]
i am having the exact same issue. looks like its been a year since anyone said anything. has anyone found a solution for this? its ashame that they dont want u to email them for any kind of help or support  and to use their "discord" server..    wat a joke.   nice support project lunar......

**Comment by ChibiANUBIS** [comment]
Same for me
