### ISSUE TITLE
Cannot open game manager

### ISSUE THREAD

**Issue by christianbeland** [Project-Lunar/Project-Lunar-Issue-Tracker#34]
I see the following error in log after i tried to open the game manager:

`Renci.SshNet.Common.ScpException: scp: /usr/game/m2engage: No such file or directory
   at Renci.SshNet.ScpClient.ReadString(Stream stream)
   at Renci.SshNet.ScpClient.InternalDownload(IChannelSession channel, Stream input, FileSystemInfo fileSystemInfo)
   at Renci.SshNet.ScpClient.Download(String filename, FileInfo fileInfo)
   at ProjectLunarUI.frmGameManager.FrmGameManager_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by reptor1304** [comment]
I have the same issue. 
ci.SshNet.Common.ScpException: scp: /usr/game/m2engage: No such file or directory
   at Renci.SshNet.ScpClient.ReadString(Stream stream)
   at Renci.SshNet.ScpClient.InternalDownload(IChannelSession channel, Stream input, FileSystemInfo fileSystemInfo)
   at Renci.SshNet.ScpClient.Download(String filename, FileInfo fileInfo)
   at ProjectLunarUI.frmGameManager.FrmGameManager_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Also I cannot install update from game manager

**Comment by ChibiANUBIS** [comment]
Same for me
